# Generated by Django 3.2.4 on 2021-06-12 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRepresentatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('products', models.ManyToManyField(related_name='products_services', to='accounts.ProductService')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
