# Generated by Django 3.2.4 on 2021-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_productservice_supplierrepresentatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrepresentatives',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
