# Generated by Django 3.2.4 on 2021-06-12 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_supplierrepresentatives_primary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierrepresentatives',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
