name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: flake8 Linter
        run: pip install flake8 && flake8 --exclude 'venv,.venv,env,.env' --statistics --count --ignore=E501

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: django test
        run: ./manage.py test

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: |
          git init
          git config user.name "deploy"
          git config user.email "deploy@localhost"
          git add .
          git commit -m "automated deploy"
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku HEAD:master -f
